# Generated by Django 4.2.3 on 2023-07-11 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Vin')),
                ('color', models.CharField(max_length=64, verbose_name='Color')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('breed', models.IntegerField(choices=[(1, 'Кошка'), (2, 'Собака'), (3, 'Попугай'), (4, 'Змея'), (5, 'Крыса'), (6, 'Ящерица')], verbose_name='Breed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
